### ISSUE TITLE
error npm start 

### ISSUE THREAD

**Issue by Grezor** [rbhatia46/React-Portfolio#13]
I've been on my vscode
it detects errors 

I typed the commands: 
npm i 
npm start 

![image](https://user-images.githubusercontent.com/38507456/107847331-e499ed80-6dea-11eb-9d95-9bceb063d4e6.png)

**Comment by EwelinaL96** [comment]
Lgdhj

**Comment by ameyamjoshi** [comment]
I don't see errors there, those are warnings ! . You can still see react app running on localhost:3000
